---
  apiVersion: v1

  webhook: github

  ip_range: 
    # obtained from https://api.github.com/meta
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"
    - "143.55.64.0/20"
    - "2a0a:a440::/29"
    - "2606:50c0::/32"

  repository:
    - name: dingp/acme
      user:
        - dingp
      branch:
        - main
        - development
      secret: dingp-acme-github-webhook-secret
      cluster:
        perlmutter:
          host: perlmutter.nersc.gov
          account: cce
          protocol: sfapi
          sfapi_jwt: hep-cce-sfapi-jwt
