---
  apiVersion: v1

  webhook: github

  ip_range: 
    # obtained from https://api.github.com/meta
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"
    - "143.55.64.0/20"
    - "2a0a:a440::/29"
    - "2606:50c0::/32"

  repository:
    - name: dingp/acme
      user:
        - dingp
      branch:
        - main
        - development
      webhook_secret: /secrets/dingp/acme/webhook
      cluster:
        perlmutter:
          host: perlmutter.nersc.gov
          account: dingpf
          protocol: sfapi
          client_id: /secrets/dingp/acme/sfapi.client_id.txt
          private_key: /secrets/dingp/acme/sfapi.priv_key.pem
    - name: hep-cce/FCS-GPU
      user:
        - dingp
        - cgleggett
        - lorenz369
      branch:
        - main
        - development
      webhook_secret: /secrets/hep-cce/FCS-GPU/webhook
      cluster:
        perlmutter:
          host: perlmutter.nersc.gov
          account: cce
          protocol: sfapi
          client_id: /secrets/hep-cce/FCS-GPU/sfapi.client_id.txt
          private_key: /secrets/hep-cce/FCS-GPU/sfapi.priv_key.pem
